# Generated by Django 4.1.1 on 2022-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=4)),
                ('sname', models.CharField(max_length=255)),
                ('scontact', models.CharField(max_length=15)),
            ],
        ),
    ]
